[package]
authors = ["Zack Owens <zowens2009@gmail.com>"]
name = "paxos"
version = "0.1.0"
build = "build.rs"

[dependencies]
log = "0.3.8"
rand = "0.3.18"
tokio-core = "0.1.11"
futures = "0.1.17"
env_logger = "0.4.3"
capnp = "0.8.13"
futures-timer = { git = "https://github.com/alexcrichton/futures-timer.git" }

[dev-dependencies]
assert_matches = "1.1.0"

[build-dependencies]
capnpc = "0.8"
