[package]
authors = ["Zack Owens <zowens2009@gmail.com>"]
name = "paxos"
version = "0.1.0"

[dependencies]
log = "0.4"
rand = "0.4"
tokio-core = "0.1.11"
futures = "0.1.17"
env_logger = "0.4.3"
futures-timer = { git = "https://github.com/alexcrichton/futures-timer.git" }
clap = "2.29.0"
either = "1.4.0"
tokio-io = "0.1.4"
serde_derive = "1.0.26"
serde_cbor = "0.8.1"
serde = "1.0.26"

[dev-dependencies]
assert_matches = "1.1.0"
